
spring:
  profiles:
    active: local
    group:
      local: aws-sqs-common, aws-sqs-local
      aws: aws-sqs-common


cloud:
  aws:
    static:
      region: sa-east1

application:
  aws:
    queue: recebimento-bacen
